
-- Generated by ORDS REST Data Services 23.1.0.r0861423
-- Schema: HR  Date: Sáb Jul 06 05:50:05 2024 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'HR',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'apex_xepdb1',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'barbieapex24.br',
      p_base_path      => '/barbie/',
      p_items_per_page => 15,
      p_status         => 'PUBLISHED',
      p_comments       => 'Projeto Barbie APEX 24 | Aprendendo um pouco de Oracle Apex com a Barbie.');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'barbieapex24.br',
      p_pattern        => 'clientes/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'barbieapex24.br',
      p_pattern        => 'clientes/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 10,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select 
 cli_id "$uri",
 cli_id,
 nome,
 sobrenome,
 apelido,
 documento,
 endereco,
 data_criacao,
 dt_nascimento,
 tp_documento,
 tp_sanguineo,
 time_favorito,
 atividades,
 --desenho_favorito,
 tenho_pet,
 pet_lover,
 tipo_filme,
 cor_favorita,
 nome_livro
 from cliente');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'barbieapex24.br',
      p_pattern        => 'clientes/:cli_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'barbieapex24.br',
      p_pattern        => 'clientes/:cli_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 10,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select 
 cli_id,
 nome,
 sobrenome,
 apelido,
 documento,
 endereco,
 data_criacao,
 dt_nascimento,
 tp_documento,
 tp_sanguineo,
 time_favorito,
 atividades,
 --desenho_favorito,
 tenho_pet,
 pet_lover,
 tipo_filme,
 cor_favorita,
 nome_livro
 from cliente 
 where cli_id = :cli_id');

    
        
COMMIT;

END;